module.exports = {
  MAP_WIDTH: 2000,
  MAP_HEIGHT: 1500,

  STARTING_LIVES: 10,
  MAX_PLAYERS: 6,

  TICK_RATE: 60,
  BROADCAST_RATE: 20,

  SHIP_SPEED: 5,
  SHIP_RADIUS: 18,
  SHIP_ROTATION_SPEED: 0.08,

  BULLET_SPEED: 10,
  BULLET_RADIUS: 3,
  BULLET_LIFETIME: 90, // ticks

  ASTEROID_SPEED_MIN: 1,
  ASTEROID_SPEED_MAX: 3,
  ASTEROID_RADIUS_LARGE: 40,
  ASTEROID_RADIUS_MEDIUM: 25,
  ASTEROID_RADIUS_SMALL: 14,

  WAVE_INTERVAL: 15000, // ms
  WAVE_BASE_COUNT: 4,
  WAVE_INCREMENT: 2,

  ROOM_CODE_LENGTH: 4,

  RESPAWN_INVINCIBILITY: 120, // ticks (2s at 60fps)

  PLAYER_COLORS: ['#00ffff', '#ff6600', '#ff00ff', '#00ff66', '#ffff00', '#ff3366'],

  SCORE_SMALL: 30,
  SCORE_MEDIUM: 20,
  SCORE_LARGE: 10,

  UPGRADE_POINTS_PER_WAVE: 4,
  UPGRADE_COST_MOVE_SPEED: 1,
  UPGRADE_COST_ATTACK_SPEED: 1,
  UPGRADE_COST_SHIELD: 1,
  UPGRADE_COST_DUAL_CANNON: 4,
  MOVE_SPEED_BONUS: 1,
  ATTACK_SPEED_BONUS: 1,
  MIN_SHOOT_COOLDOWN: 3,
  MAX_MOVE_SPEED_LEVEL: 5,
  MAX_ATTACK_SPEED_LEVEL: 5,
  DUAL_CANNON_SPREAD: 0.08,
};
