module.exports = {
  MAP_WIDTH: 2000,
  MAP_HEIGHT: 1500,

  STARTING_LIVES: 10,
  MAX_PLAYERS: 6,

  TICK_RATE: 60,
  BROADCAST_RATE: 20,

  SHIP_SPEED: 3,
  SHIP_RADIUS: 18,
  SHIP_ROTATION_SPEED: 0.07,

  BULLET_SPEED: 10,
  BULLET_RADIUS: 3,
  BULLET_LIFETIME: 90, // ticks

  ASTEROID_SPEED_MIN: 1,
  ASTEROID_SPEED_MAX: 3,
  ASTEROID_RADIUS_LARGE: 40,
  ASTEROID_RADIUS_MEDIUM: 25,
  ASTEROID_RADIUS_SMALL: 14,

  WAVE_INTERVAL: 15000, // ms
  WAVE_BASE_COUNT: 4,
  WAVE_INCREMENT: 2,

  ROOM_CODE_LENGTH: 4,

  RESPAWN_INVINCIBILITY: 120, // ticks (2s at 60fps)

  PLAYER_COLORS: ['#00ffff', '#ff6600', '#ff00ff', '#00ff66', '#ffff00', '#ff3366'],

  SCORE_SMALL: 30,
  SCORE_MEDIUM: 20,
  SCORE_LARGE: 10,

  UPGRADE_POINTS_PER_WAVE: 4,
  UPGRADE_COST_MOVE_SPEED: 1,
  UPGRADE_COST_ATTACK_SPEED: 1,
  UPGRADE_COST_SHIELD: 1,
  UPGRADE_COST_DUAL_CANNON: 4,
  MOVE_SPEED_BONUS: 1,
  ATTACK_SPEED_BONUS: 1,
  MIN_SHOOT_COOLDOWN: 3,
  MAX_MOVE_SPEED_LEVEL: 5,
  MAX_ATTACK_SPEED_LEVEL: 5,
  DUAL_CANNON_SPREAD: 0.08,

  // Swarm Defense mode
  SD_BASE_RADIUS: 60,
  SD_BASE_HP: 50,
  SD_BASE_HP_INCREMENT: 10,
  SD_SWARM_COUNT: 100,
  SD_SWARM_INCREMENT: 100,
  SD_SWARM_SPEED_MIN: 3,
  SD_SWARM_SPEED_MAX: 5,
  SD_SPAWN_INTERVAL: 8,
  SD_SPAWN_BATCH: 3,
  SD_SCORE_PER_ASTEROID: 15,
  SD_WAVE_COMPLETE_BONUS: 100,

  // Typing Defense mode
  TD_BASE_Y: 1350,
  TD_BASE_WIDTH: 1600,
  TD_BASE_HEIGHT: 20,
  TD_BASE_HP: 15,
  TD_BASE_HP_INCREMENT: 5,
  TD_ASTEROID_COUNT: 120,
  TD_ASTEROID_INCREMENT: 30,
  TD_ASTEROID_SPEED_MIN: 0.8,
  TD_ASTEROID_SPEED_MAX: 1.8,
  TD_SPAWN_MARGIN: 200,
  TD_WAVE_PAUSE_TICKS: 180,
  TD_SCORE_PER_ASTEROID: 20,
  TD_WORD_COMPLETE_BONUS: 50,
  TD_WAVE_COMPLETE_BONUS: 100,
  TD_BULLET_SPEED: 18,

  // Planet Killer mode
  PK_BASE_RADIUS: 200,
  PK_RADIUS_INCREMENT: 30,
  PK_MAX_RADIUS: 800,
  PK_MIN_RADIUS: 40,
  PK_BASE_HP: 30,
  PK_HP_INCREMENT: 20,
  PK_ASTEROID_SPEED: 2,
  PK_VERTEX_COUNT: 16,
  PK_SCORE_PER_HP: 5,
  PK_SCORE_KILL_BONUS: 50,
};
