module.exports = [
  // 3-4 letter words
  'fire', 'star', 'rock', 'ship', 'beam', 'dust', 'void', 'nova', 'core', 'flux',
  'bolt', 'wave', 'burn', 'glow', 'dark', 'spin', 'warp', 'rush', 'fury', 'blast',
  'hawk', 'iron', 'jade', 'acid', 'apex', 'axis', 'bane', 'barb', 'bite', 'bone',
  'cage', 'calm', 'cape', 'claw', 'coil', 'daze', 'dome', 'dusk', 'echo', 'edge',
  'fang', 'fate', 'fist', 'fold', 'fume', 'fuse', 'gale', 'gate', 'gear', 'grit',
  'hail', 'haze', 'helm', 'hilt', 'howl', 'hull', 'hunt', 'husk', 'iris', 'jolt',
  'keel', 'knot', 'lash', 'lava', 'leap', 'link', 'lock', 'loom', 'lure', 'mace',
  'mars', 'melt', 'mesh', 'mist', 'moan', 'moon', 'nail', 'neon', 'nest', 'node',
  'oath', 'onyx', 'orb', 'pact', 'pale', 'peak', 'pier', 'pike', 'ploy', 'prow',
  'rage', 'raid', 'rank', 'rift', 'rind', 'risk', 'roam', 'root', 'ruin', 'rune',
  'rust', 'sage', 'salt', 'scar', 'scud', 'seal', 'seam', 'silk', 'silo', 'sink',
  'slag', 'slew', 'slot', 'snap', 'soar', 'soot', 'soul', 'spur', 'stem', 'stun',
  'sulk', 'sway', 'tang', 'tarn', 'tear', 'thorn', 'tide', 'tomb', 'tone', 'trap',
  'tusk', 'veil', 'vent', 'vice', 'vine', 'volt', 'wake', 'wall', 'wasp', 'weld',
  'whip', 'wick', 'wild', 'wind', 'wing', 'wisp', 'writ', 'yawn', 'yell', 'zero',
  'zinc', 'zone', 'zoom',

  // 5 letter words
  'crash', 'drift', 'flame', 'laser', 'orbit', 'power', 'pulse', 'radar', 'solar',
  'space', 'steel', 'storm', 'surge', 'swift', 'titan', 'trail', 'vapor', 'venom',
  'blaze', 'chunk', 'comet', 'crack', 'crush', 'depth', 'ember', 'flare', 'frost',
  'grind', 'heavy', 'hover', 'light', 'lunar', 'metal', 'minor', 'phase', 'pilot',
  'quake', 'rapid', 'rogue', 'scale', 'shard', 'shell', 'shock', 'slash', 'slice',
  'smoke', 'solid', 'sonic', 'spark', 'speed', 'spike', 'split', 'stone', 'super',
  'toxic', 'track', 'turbo', 'ultra', 'unity', 'upper', 'vigor', 'force', 'guard',
  'honor', 'lance', 'might', 'nerve', 'omega', 'prime', 'reign', 'scope', 'siege',
  'alpha', 'armor', 'blade', 'brave', 'chain', 'claim', 'crest', 'crown', 'delta',
  'eagle', 'faint', 'gamma', 'ghost', 'globe', 'grace', 'karma', 'latch', 'march',
  'north', 'ozone', 'quest', 'rebel', 'salvo', 'abbey', 'abyss', 'agile', 'alloy',
  'angel', 'anvil', 'arena', 'arrow', 'atlas', 'awake', 'badge', 'basil', 'beach',
  'beast', 'black', 'bloom', 'blunt', 'board', 'brace', 'brass', 'brawn', 'break',
  'breed', 'briar', 'brine', 'brisk', 'broad', 'brook', 'brute', 'build', 'burst',
  'cabal', 'cargo', 'cedar', 'chaos', 'charm', 'chase', 'cheap', 'chief', 'chord',
  'clamp', 'clash', 'clear', 'climb', 'cling', 'cloak', 'close', 'cloud', 'coach',
  'cobra', 'coral', 'count', 'court', 'crane', 'crawl', 'creep', 'cross', 'crude',
  'cruel', 'curse', 'cycle', 'death', 'decay', 'decoy', 'demon', 'dense', 'ditch',
  'dodge', 'draft', 'drain', 'drake', 'drape', 'dread', 'drive', 'drone', 'drown',
  'dwarf', 'earth', 'elbow', 'elder', 'elfin', 'elude', 'envoy', 'epoch', 'equip',
  'erase', 'erupt', 'evade', 'event', 'exalt', 'exile', 'expel', 'extra', 'faith',
  'feast', 'fence', 'fiend', 'filth', 'final', 'fjord', 'flash', 'flesh', 'flint',
  'flock', 'flood', 'floor', 'flora', 'fluid', 'forge', 'found', 'frame', 'frank',
  'freak', 'fresh', 'front', 'gauge', 'gears', 'giant', 'glare', 'gleam', 'glide',
  'glint', 'gloom', 'golem', 'gorge', 'grasp', 'grass', 'grave', 'greed', 'green',
  'grief', 'grove', 'growl', 'guild', 'guise', 'gulch', 'glyph', 'haven', 'heist',
  'heron', 'hoard', 'horde', 'horse', 'humid', 'hydra', 'hyper', 'ichor', 'image',
  'impel', 'inert', 'inner', 'ivory', 'jewel', 'joust', 'judge', 'knack', 'knave',
  'knife', 'krait', 'kraken', 'labor', 'leach', 'leech', 'level', 'lever', 'llama',
  'lodge', 'lofty', 'lucid', 'lynch', 'manor', 'marsh', 'mason', 'mauve', 'maxim',
  'mercy', 'mimic', 'mirth', 'moose', 'morph', 'mortar', 'mount', 'mourn', 'mural',
  'nadir', 'nerve', 'nexus', 'night', 'noble', 'notch', 'ocean', 'ombre', 'onset',
  'opera', 'orcas', 'other', 'outer', 'oxide', 'panic', 'patch', 'peril', 'piety',
  'pivot', 'pixel', 'plain', 'plank', 'plant', 'plaza', 'plead', 'plume', 'plumb',
  'point', 'polar', 'pouch', 'pound', 'prank', 'prawn', 'press', 'price', 'pride',
  'print', 'prism', 'prize', 'probe', 'prone', 'proof', 'prowl', 'punch', 'purge',
  'queen', 'query', 'quick', 'quiet', 'quota', 'raven', 'reach', 'realm', 'reap',
  'reign', 'remit', 'ridge', 'rivet', 'roost', 'round', 'royal', 'saint', 'savor',
  'scalp', 'scorn', 'scout', 'scrap', 'scrub', 'serve', 'seven', 'shade', 'shaft',
  'shame', 'shape', 'shark', 'sharp', 'shear', 'sheet', 'shift', 'shine', 'shire',
  'shoal', 'shore', 'shout', 'shrub', 'shunt', 'siege', 'sight', 'sigma', 'siren',
  'skull', 'sleek', 'slide', 'sling', 'sloth', 'smash', 'smelt', 'smith', 'snare',
  'south', 'spade', 'spare', 'spawn', 'spear', 'spell', 'spent', 'spice', 'spine',
  'spoil', 'spore', 'squid', 'stair', 'stake', 'stalk', 'stand', 'stark', 'start',
  'stash', 'steam', 'steep', 'stern', 'still', 'stomp', 'stork', 'stout', 'stove',
  'strap', 'stray', 'strip', 'strut', 'stuck', 'stuff', 'stump', 'swamp', 'swarm',
  'sweep', 'swell', 'swirl', 'sword', 'swore', 'talon', 'tango', 'tense', 'theta',
  'thief', 'thorn', 'throw', 'tiger', 'torch', 'totem', 'tower', 'trace', 'trade',
  'trait', 'trash', 'tread', 'triad', 'tribe', 'trick', 'troop', 'truce', 'trunk',
  'trust', 'truth', 'tulip', 'twine', 'twist', 'umbra', 'uncap', 'under', 'undid',
  'unify', 'union', 'unite', 'untie', 'usurp', 'valve', 'vault', 'verge', 'vigor',
  'viper', 'visor', 'vital', 'vivid', 'vouch', 'wagon', 'watch', 'water', 'wheat',
  'where', 'whirl', 'widen', 'witch', 'world', 'worth', 'wound', 'wrack', 'wrath',
  'yield', 'young',

  // 6 letter words
  'sector', 'anchor', 'bandit', 'beacon', 'canyon', 'debris', 'engine', 'falcon',
  'galaxy', 'hazard', 'impact', 'jungle', 'launch', 'magnet', 'nebula', 'patrol',
  'quasar', 'rocket', 'shield', 'target', 'vector', 'wraith', 'astral', 'breach',
  'cipher', 'defend', 'energy', 'fusion', 'gunner', 'hunter', 'ignite', 'jammer',
  'knight', 'legend', 'meteor', 'recoil', 'turret', 'weapon', 'plasma', 'strike',
  'danger', 'combat', 'hammer', 'shadow', 'sniper', 'absorb', 'ambush', 'arctic',
  'armada', 'atomic', 'baffle', 'barbed', 'barrel', 'battle', 'bellow', 'betray',
  'bitter', 'bonfire', 'border', 'bounty', 'broken', 'bronze', 'buckle', 'bullet',
  'bunker', 'burden', 'canopy', 'carbon', 'castle', 'cavern', 'charge', 'chrome',
  'cleric', 'cobalt', 'coffin', 'colony', 'concur', 'condor', 'copper', 'corner',
  'cosmic', 'coyote', 'cradle', 'crater', 'crisis', 'crusoe', 'custom', 'cutoff',
  'dagger', 'damage', 'deacon', 'decode', 'decree', 'defect', 'deluge', 'demise',
  'deploy', 'desert', 'detach', 'devour', 'disarm', 'divine', 'domain', 'dragon',
  'duress', 'dynamo', 'effigy', 'emerge', 'enable', 'engage', 'enigma', 'ensign',
  'errand', 'escape', 'evince', 'evolve', 'exceed', 'exempt', 'expand', 'expert',
  'expose', 'falcon', 'famine', 'ferret', 'fierce', 'flight', 'flurry', 'forage',
  'forged', 'fossil', 'freeze', 'frigate', 'frozen', 'gadget', 'gallop', 'gambit',
  'garnet', 'gauntlet', 'glitch', 'goblet', 'golden', 'gravel', 'geyser', 'grovel',
  'hallow', 'harbor', 'harken', 'havoc', 'healer', 'helmet', 'hidden', 'hinder',
  'hollow', 'horror', 'hybrid', 'icicle', 'illume', 'immune', 'impale', 'impose',
  'infect', 'inferno', 'inject', 'insect', 'intent', 'invade', 'invent', 'island',
  'jackal', 'jagged', 'jostle', 'juggle', 'keeper', 'kindle', 'lament', 'lethal',
  'lichen', 'locker', 'locust', 'magnum', 'malice', 'mangle', 'mantle', 'marine',
  'maroon', 'medusa', 'menace', 'minion', 'mortal', 'mutant', 'mystic', 'nimble',
  'oracle', 'outlaw', 'palace', 'pardon', 'pellet', 'pirate', 'plague', 'plunge',
  'poison', 'portal', 'potent', 'powder', 'primal', 'prince', 'prison', 'pummel',
  'python', 'quartz', 'radial', 'raider', 'ramble', 'rampart', 'ransom', 'ravage',
  'reckon', 'redeye', 'reflex', 'remote', 'render', 'resist', 'revolt', 'ripple',
  'ritual', 'rodent', 'rubble', 'rumble', 'rugged', 'rustic', 'sabote', 'salute',
  'savage', 'scarab', 'scorch', 'scroll', 'sentry', 'serene', 'shogun', 'signal',
  'silver', 'simple', 'sinker', 'skull', 'slayer', 'socket', 'solder', 'sorrow',
  'sphinx', 'spider', 'spiral', 'splice', 'squall', 'squire', 'stalks', 'statue',
  'steady', 'stitch', 'stoker', 'strand', 'strife', 'summit', 'summon', 'sunset',
  'supply', 'switch', 'symbol', 'tactic', 'tangle', 'temple', 'tender', 'thirst',
  'thrash', 'threat', 'throne', 'timber', 'tongue', 'torque', 'treaty', 'tribal',
  'trophy', 'tundra', 'tunnel', 'tyrant', 'undead', 'unfold', 'unlock', 'unrest',
  'upkeep', 'upwind', 'usable', 'vacuum', 'vandal', 'velvet', 'vessel', 'viking',
  'violet', 'vortex', 'vulcan', 'walrus', 'wander', 'warden', 'warrior', 'weasel',
  'whisky', 'wicker', 'winter', 'wizard', 'wonder', 'wrench', 'zenith', 'zephyr',
  'zodiac',

  // 7+ letter words
  'thunder', 'panther', 'kinetic', 'outpost', 'neutron', 'photon', 'valiant', 'stealth',
  'victory', 'abandon', 'absolve', 'achieve', 'alchemy', 'allegro', 'ancient', 'android',
  'antenna', 'apparel', 'archive', 'assault', 'auditor', 'aviator', 'backlash', 'balance',
  'ballast', 'bandage', 'banshee', 'baptize', 'barrage', 'bastion', 'battery', 'bedrock',
  'berserk', 'bestial', 'between', 'biomass', 'blacken', 'blanket', 'blaster', 'blazing',
  'blocked', 'blowout', 'booster', 'borough', 'bravado', 'bravery', 'breaker', 'brigand',
  'bristle', 'bromine', 'bucking', 'bulwark', 'cadence', 'caliber', 'captain', 'capture',
  'carbine', 'carrion', 'cascade', 'casket', 'cavalry', 'caution', 'centaur', 'chamber',
  'channel', 'chapter', 'chariot', 'chimera', 'citadel', 'cluster', 'cockpit', 'cohabit',
  'collide', 'command', 'compact', 'complex', 'conceal', 'concern', 'conduct', 'confine',
  'conquer', 'console', 'consume', 'content', 'control', 'convert', 'corsair', 'counter',
  'courage', 'crafter', 'cryptic', 'crystal', 'current', 'cyclone', 'darkest', 'deadlock',
  'decider', 'decrypt', 'default', 'defense', 'deflect', 'deliver', 'despair', 'destine',
  'destroy', 'detract', 'diamond', 'disable', 'disband', 'discord', 'display', 'disrupt',
  'distant', 'diverge', 'dominate', 'dungeon', 'dynasty', 'eclipse', 'elation', 'element',
  'embargo', 'embassy', 'empower', 'enchant', 'enforce', 'engrave', 'entropy', 'epsilon',
  'erosion', 'eternal', 'evasion', 'evident', 'exactly', 'exhaust', 'exploit', 'extreme',
  'fallout', 'fighter', 'firefly', 'fission', 'flanker', 'flicker', 'flutter', 'footman',
  'foreign', 'forfeit', 'fortune', 'forward', 'fractal', 'fracture', 'fragile', 'freedom',
  'freight', 'furnace', 'gadgets', 'galleon', 'gambler', 'gateway', 'general', 'genesis',
  'gladius', 'grapple', 'gravity', 'grenade', 'griffin', 'gryphon', 'guerdon', 'gunboat',
  'habitat', 'halberd', 'hallway', 'handful', 'harbinger', 'hardship', 'harmony', 'harvest',
  'hastily', 'haunted', 'hellion', 'heretic', 'horizon', 'hostile', 'howitzer', 'impulse',
  'incline', 'inferno', 'inhabit', 'inspect', 'instill', 'inverse', 'ironclad', 'isolate',
  'javelin', 'journey', 'kingdom', 'lantern', 'lateral', 'lattice', 'leopard', 'liberty',
  'lookout', 'machete', 'mammoth', 'mandate', 'massive', 'mercury', 'militia', 'mineral',
  'missile', 'mission', 'monitor', 'monster', 'mustang', 'mystery', 'naphtha', 'nothing',
  'nucleus', 'nullify', 'obscure', 'offense', 'operate', 'optimal', 'outlast', 'outlook',
  'overrun', 'paragon', 'patriot', 'payload', 'pelagic', 'penalty', 'percuss', 'phantom',
  'phoenix', 'pilgrim', 'pinnacle', 'plaster', 'platoon', 'plunder', 'polaris', 'precede',
  'predict', 'prelude', 'prevail', 'primate', 'prodigy', 'program', 'project', 'promise',
  'propane', 'protect', 'protest', 'provoke', 'pursuit', 'quantum', 'quarrel', 'quarter',
  'rampage', 'reactor', 'rebuild', 'recover', 'recruit', 'reflect', 'refugee', 'remnant',
  'repulse', 'require', 'reserve', 'resolve', 'restore', 'retract', 'reunite', 'revenge',
  'revolve', 'riposte', 'riveted', 'runaway', 'rupture', 'sabotage', 'salvage', 'sanctum',
  'scanner', 'scarlet', 'scatter', 'scourge', 'seafare', 'serpent', 'session', 'shatter',
  'shelter', 'shining', 'silence', 'sinuous', 'smother', 'soldier', 'spartan', 'specter',
  'spelunk', 'splashy', 'squeeze', 'stalwart', 'starlit', 'station', 'stopper', 'strange',
  'striker', 'stumble', 'subject', 'subvert', 'sunburn', 'supreme', 'surface', 'surplus',
  'survive', 'suspend', 'tempest', 'terrain', 'thermal', 'thicket', 'torpedo', 'torrent',
  'tracker', 'traitor', 'trample', 'transit', 'trigger', 'trilogy', 'triumph', 'turbine',
  'twister', 'typhoon', 'unbound', 'undying', 'unicorn', 'unknown', 'unleash', 'upright',
  'uranium', 'vagrant', 'vampire', 'vanguard', 'venture', 'verdict', 'veteran', 'voltage',
  'voyager', 'vulture', 'warhead', 'warlock', 'warpath', 'warrior', 'weather', 'western',
  'wildcat', 'withdraw', 'witness', 'wolfram', 'wyvern', 'zealous',
];
